"""Pydantic models — canonical structure for every component kind in hw-registry."""

from .board import Board, BuildSpec, ExpansionHeader, Peripherals
from .chip import Chip, CoreSpec
from .common import (
    COMPONENT_ID_REGEX,
    COMPONENT_REF_REGEX,
    SEMVER_REGEX,
    AltFunction,
    Asset,
    AssetBundle,
    CurrentDraw,
    Datasheet,
    Discovery,
    Electrical,
    ExternalRefs,
    Identifiable,
    Interface,
    InterfaceType,
    KicadRefs,
    Kind,
    Lifecycle,
    LogicSpec,
    Package,
    PackageDimensions,
    Pin,
    PinDirection,
    Strict,
    Tested,
    TestedStatus,
    UsbId,
    VccSource,
    VccSpec,
)
from .connector import Connector, ConnectorPin, Gender, Mounting
from .driver import Driver, DriverBinding, Framework
from .module import ContainedPart, FirmwareOption, Module
from .sensor import (
    I2CConstraints,
    InterruptConstraint,
    PowerConstraints,
    Sensor,
    SensorConstraints,
    SPIConstraints,
    TempRange,
    UARTConstraints,
    VoltageRange,
)

__all__ = [
    "COMPONENT_ID_REGEX",
    "COMPONENT_REF_REGEX",
    "SEMVER_REGEX",
    "AltFunction",
    "Asset",
    "AssetBundle",
    "Board",
    "BuildSpec",
    "Chip",
    "Connector",
    "ConnectorPin",
    "ContainedPart",
    "CoreSpec",
    "CurrentDraw",
    "Datasheet",
    "Discovery",
    "Driver",
    "DriverBinding",
    "Electrical",
    "ExpansionHeader",
    "ExternalRefs",
    "FirmwareOption",
    "Framework",
    "Gender",
    "I2CConstraints",
    "Identifiable",
    "Interface",
    "InterfaceType",
    "InterruptConstraint",
    "KicadRefs",
    "Kind",
    "Lifecycle",
    "LogicSpec",
    "Module",
    "Mounting",
    "Package",
    "PackageDimensions",
    "Peripherals",
    "Pin",
    "PinDirection",
    "PowerConstraints",
    "SPIConstraints",
    "Sensor",
    "SensorConstraints",
    "Strict",
    "TempRange",
    "Tested",
    "TestedStatus",
    "UARTConstraints",
    "UsbId",
    "VccSource",
    "VccSpec",
    "VoltageRange",
]
